# Generated by Django 3.0.4 on 2020-03-12 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20200312_0357'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Watchlinks',
            new_name='MovieLink',
        ),
    ]
